### ISSUE TITLE
Connect Stargate With Dotnet Core

### ISSUE THREAD

**Issue by ImAbhishekTomar** [stargate/api-extensions#13]
Anyone please 🙏  help me to understand this 🤯 Stargate.

My organisation is protecting all rest api using this stargate thing and my organisation most of the api is based on the java but now they gave me a project that have many dot net core API without any authentication that I want to protect with this stargate auth.

On my enterprise GitHub I submit some PR and they give me a proxy JSON file (proxy file have ProxyUrl and other proper and proxyurl is auto created by stargate guthub not) with namespace json file that have client token for consumers I really don't know how can I connect my api with this stargate and protect API with this and validate incoming toke coming from OAuth.

Thanks!! in advance

https://stackoverflow.com/q/67204985/4208247

**NAME-SAPCE-JSON**

    {
      "kind": "stargate-team",
      "spec": {
        "id": "0000000000000000000000000000",
        "credentials": [
          {
            "env": "prod",
            "oauthClientId": "0000000000000000000000000",
            "oauthClientSecret": "0000000000000000000000000",
            "jwtKey": "0000000000000000000000000",
            "jwtSecret": "0000000000000000000000000"
          },
          {
            "env": "nonprod",
            "oauthClientId": "0000000000000000000000000",
            "oauthClientSecret": "0000000000000000000000000",
            "jwtKey": "0000000000000000000000000",
            "jwtSecret": "0000000000000000000000000"
          }
        ]
      },
      "metadata": {
        "namespace": "umr.automations.api"
      }
    }

**PROXY-JSON**

    {
      "kind": "stargate-proxy",
      "action": "create",
      "spec": {
        "name": "dx.stage.proxy",
        "routeId": "**********************",
        "serviceId": "**********************",
        "url": "http://**********************/api-stargatedev",
        "proxyUrl": "https://abc-stage-core.company.com"/api/dev/clm/auto.api/v1.0",
        "auth": [
          {
            "type": "jwt"
          },
          {
            "type": "oauth2",
            "grant": "client_credentials"
          }
        ],
        "connectTimeout": 2000,
        "readTimeout": 9000,
        "writeTimeout": 9000,
        "authorizedConsumers": [
          "umr.automations.api"
        ],
        "mtlsUpstreamRouting": false
      },
      "metadata": {
        "namespace": "auto.api",
        "proxyUrl": {
          "host": "gateway-stage-core.company.com",
          "domain": "claims",
          "env": "dev",
          "namespace": "auto.api",
          "version": "v1.0",
          "type": "api"
        },
        "certificationFileName": ""
      }
    }

**Comment by dougwettlaufer** [comment]
Hi @ImAbhishekTomar are you sure you have the correct project? This [stargate](https://stargate.io) is a data gateway for Apache Cassandra and DSE that provides REST, Graphql, and CQL APIs. It does support JWT based auth for its own REST API but this is not intended to protect other APIs. 

This particular repo has also been deprecated for several months and all active development has been moved to stargate/stargate.
